"""Run-time roster input (PLAN.md §4.2).

The roster is never stored in the repository. It is read from a file (or stdin) in one
of two formats:

1. **Group-Members text** — the format of the group's "Group Members" document::

       Current Group Members:
       * Firstname Lastname (0000-0000-0000-0000)
       Joint Appointments:
       * Firstname Lastname (Institution; 0000-0000-0000-0000)
       Affiliated Postdocs:
       * ...
       Affiliated Students:
       * ...
       Former Members:
       * ...
       Known Name Conflicts:
       * Firstname Lastname: Other Person (field); Another Person.

   Lines outside recognised sections (preamble, "Projects ...", etc.) are ignored.
   Only bulleted entries (``*``, ``-`` or ``•``) are read.

2. **YAML / JSON** — a list of :class:`~talk_tracker.models.RosterEntry` mappings, or a
   mapping with an ``entries`` key.

Name variants are generated by :func:`name_variants`. All variants are returned in
normalised form (:func:`normalize_name`), so matching must normalise the text it
searches in the same way.
"""

from __future__ import annotations

import json
import re
import sys
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path

import yaml
from pydantic import ValidationError

from .models import Role, Roster, RosterEntry


class RosterError(ValueError):
    """Raised when a roster cannot be parsed; message includes the line number if known."""


# --------------------------------------------------------------------------- ORCID

_ORCID_RE = re.compile(r"\b(\d{4}-\d{4}-\d{4}-\d{3}[\dX])\b")


def orcid_checksum_ok(orcid: str) -> bool:
    """ISO 7064 11,2 check digit, as used by ORCID."""
    digits = orcid.replace("-", "")
    if not re.fullmatch(r"\d{15}[\dX]", digits):
        return False
    total = 0
    for ch in digits[:-1]:
        total = (total + int(ch)) * 2
    result = (12 - total % 11) % 11
    check = "X" if result == 10 else str(result)
    return digits[-1] == check


def validate_orcid(orcid: str) -> str:
    orcid = orcid.strip().upper()
    orcid = re.sub(r"^HTTPS?://ORCID\.ORG/", "", orcid)
    if not re.fullmatch(r"\d{4}-\d{4}-\d{4}-\d{3}[\dX]", orcid):
        raise ValueError(f"malformed ORCID iD {orcid!r}")
    if not orcid_checksum_ok(orcid):
        raise ValueError(f"ORCID iD {orcid!r} fails checksum")
    return orcid


# --------------------------------------------------------------------------- names

_SEPARATORS = re.compile(r"[\s\-‐‑‒–—.,]+")


def normalize_name(text: str) -> str:
    """NFKD, strip accents, casefold, unify hyphens/dots/commas/whitespace to single spaces."""
    decomposed = unicodedata.normalize("NFKD", text)
    stripped = "".join(c for c in decomposed if not unicodedata.combining(c))
    return _SEPARATORS.sub(" ", stripped.casefold()).strip()


def _is_initial(token: str) -> bool:
    return bool(re.fullmatch(r"\w\.?", token)) or bool(re.fullmatch(r"(\w\.)+", token))


@dataclass(frozen=True)
class NameVariants:
    """Normalised variants of one person's name.

    ``full`` variants contain a given name spelled out and are strong evidence;
    ``initials`` variants (initial(s) + surname) are weak evidence and need an
    affiliation check at matching time (PLAN.md §5.5).
    """

    full: frozenset[str]
    initials: frozenset[str]
    surnames: frozenset[str]


def name_variants(name: str, extra: list[str] | tuple[str, ...] = ()) -> NameVariants:
    """Generate variants for ``name`` ("Given [Middle ...] Surname").

    The surname is taken to be the last token. Compound surnames without a hyphen
    (e.g. two Spanish surnames) are therefore only matched as written; supply further
    forms through ``extra`` (the ``variants`` field of a YAML roster).

    Generated forms:

    * the name as written;
    * the name without initials (``"C. Eric Dahl"`` → ``"Eric Dahl"``;
      ``"Jane Q. Doe"`` → ``"Jane Doe"``);
    * ``"Surname, Given"`` order (normalises to ``"surname given"``);
    * initial forms: ``"J. Doe"``, ``"J. Q. Doe"`` (and ``"E. Doe"``, ``"C. E. Doe"`` when the
      first token is itself an initial).

    Accents, hyphens, dots and case are removed by normalisation, so ``"Núñez-Ríos"``
    and ``"Nunez Rios"`` produce the same variant.
    """
    tokens = name.split()
    if len(tokens) < 2:
        raise ValueError(f"name {name!r} needs at least a given name and a surname")
    surname = tokens[-1]
    given = tokens[:-1]
    spelled = [t for t in given if not _is_initial(t)]

    full: set[str] = {normalize_name(name)}
    if spelled:
        full.add(normalize_name(" ".join([*spelled, surname])))
        full.add(normalize_name(f"{surname}, {' '.join(spelled)}"))
        # first spelled given name only, dropping further middle names
        full.add(normalize_name(f"{spelled[0]} {surname}"))

    initials: set[str] = set()
    letters = [t[0] for t in given]
    initials.add(normalize_name(f"{letters[0]}. {surname}"))
    initials.add(normalize_name(" ".join(f"{c}." for c in letters) + f" {surname}"))
    if spelled and _is_initial(given[0]):
        # goes by a middle name: "C. Eric Dahl" -> "E. Dahl"
        initials.add(normalize_name(f"{spelled[0][0]}. {surname}"))

    for v in extra:
        norm = normalize_name(v)
        vt = v.split()
        if len(vt) >= 2 and all(_is_initial(t) for t in vt[:-1]):
            initials.add(norm)
        else:
            full.add(norm)

    initials -= full
    return NameVariants(
        full=frozenset(full),
        initials=frozenset(initials),
        surnames=frozenset({normalize_name(surname)}),
    )


# --------------------------------------------------------------------------- text format

#: Heading prefix (normalised) -> role, or the special value "conflicts".
_HEADINGS: list[tuple[str, Role | str]] = [
    ("current group members", Role.member),
    ("current members", Role.member),
    ("group members", Role.member),
    ("members", Role.member),
    ("joint appointments", Role.joint),
    ("joint members", Role.joint),
    ("affiliated postdocs", Role.postdoc),
    ("postdocs", Role.postdoc),
    ("affiliated students", Role.student),
    ("students", Role.student),
    ("former members", Role.former),
    ("former group members", Role.former),
    ("known name conflicts", "conflicts"),
    ("name conflicts", "conflicts"),
]

_BULLET = re.compile(r"^\s*[*\-•]\s+(.*\S)\s*$")
_ENTRY = re.compile(r"^(?P<name>[^()]+?)\s*(?:\((?P<paren>[^)]*)\))?\s*$")
_NAME_TOKEN = re.compile(r"^[^\W\d_][\w'’\-]*\.?$|^(?:[^\W\d_]\.)+$")


def _heading(line: str) -> Role | str | None:
    """Return the section a heading line opens, ``""`` for an unknown heading, or None."""
    if _BULLET.match(line):
        return None
    head, sep, _rest = line.partition(":")
    if not sep:
        return ""
    norm = normalize_name(re.sub(r"\([^)]*\)", " ", head))  # drop "(explanatory note)"
    for prefix, section in _HEADINGS:
        if norm == prefix:
            return section
    return ""


def _looks_like_name(text: str) -> bool:
    tokens = text.split()
    return 2 <= len(tokens) <= 6 and all(_NAME_TOKEN.match(t) and t[0].isupper() for t in tokens)


_SENTENCE_END = re.compile(r"(?<![\s.]\w)(?<!^\w)\.\s+(?=[^\W\d_]{2,})")


def _parse_conflicts(rest: str) -> list[str]:
    """Extract names from ``"Other Person (field); Another Person. Free text ..."``."""
    names = []
    for piece in rest.split(";"):
        candidate = piece.split("(")[0].strip()
        # drop trailing sentence text: cut at ". " followed by a word of 2+ letters
        # (but not after an initial, as in "Jane Q. Doe")
        candidate = _SENTENCE_END.split(candidate)[0].strip().rstrip(".")
        if _looks_like_name(candidate):
            names.append(candidate)
    return names


@dataclass
class _Draft:
    name: str
    role: Role
    orcid: str | None = None
    institution: str | None = None
    line: int = 0
    not_: list[str] = field(default_factory=list)


def parse_group_members_text(text: str) -> Roster:
    drafts: list[_Draft] = []
    conflicts: list[tuple[int, str, list[str]]] = []
    section: Role | str | None = None

    for lineno, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line:
            continue
        bullet = _BULLET.match(raw)
        if not bullet:
            h = _heading(line)
            section = h if h else None
            continue
        if section is None:
            continue
        body = bullet.group(1)

        if section == "conflicts":
            who, sep, rest = body.partition(":")
            if sep:
                conflicts.append((lineno, who.strip(), _parse_conflicts(rest)))
            continue

        m = _ENTRY.match(body)
        if not m:
            raise RosterError(f"line {lineno}: cannot parse entry {body!r}")
        name = " ".join(m.group("name").split())
        orcid = institution = None
        for part in (m.group("paren") or "").split(";"):
            part = part.strip()
            if not part:
                continue
            found = _ORCID_RE.search(part)
            if found:
                orcid = found.group(1)
            elif "orcid" in part.casefold():
                continue  # e.g. "ORCID not listed"
            else:
                institution = part
        assert isinstance(section, Role)
        drafts.append(_Draft(name, section, orcid, institution, lineno))

    by_name = {normalize_name(d.name): d for d in drafts}
    for lineno, who, names in conflicts:
        target = by_name.get(normalize_name(who))
        if target is None:
            raise RosterError(f"line {lineno}: name conflict listed for unknown person {who!r}")
        target.not_.extend(names)

    entries = []
    for d in drafts:
        try:
            entries.append(
                RosterEntry(
                    name=d.name,
                    role=d.role,
                    orcid=d.orcid,
                    institution=d.institution,
                    **{"not": d.not_},
                )
            )
        except ValidationError as exc:
            msg = "; ".join(e["msg"] for e in exc.errors())
            raise RosterError(f"line {d.line}: {d.name}: {msg}") from exc
    if not entries:
        raise RosterError(
            "no roster entries found (expected bulleted lines under section headings)"
        )
    return Roster(entries=entries)


# --------------------------------------------------------------------------- structured format


def parse_structured(data: object) -> Roster:
    if isinstance(data, dict) and "entries" in data:
        data = data["entries"]
    if not isinstance(data, list):
        raise RosterError("structured roster must be a list of entries or a mapping with 'entries'")
    try:
        return Roster(entries=[RosterEntry.model_validate(e) for e in data])
    except ValidationError as exc:
        raise RosterError(str(exc)) from exc


# --------------------------------------------------------------------------- entry point


def parse_roster_text(text: str, fmt: str | None = None) -> Roster:
    """Parse roster text. ``fmt`` is ``"text"``, ``"yaml"``, ``"json"`` or None (auto)."""
    if fmt is None:
        stripped = text.lstrip()
        if stripped.startswith(("[", "{")):
            fmt = "json"
        elif re.match(r"^\s*-\s+name\s*:", text, re.M) or re.match(r"^entries\s*:", text, re.M):
            fmt = "yaml"
        else:
            fmt = "text"
    if fmt == "json":
        try:
            return parse_structured(json.loads(text))
        except json.JSONDecodeError as exc:
            raise RosterError(f"invalid JSON: {exc}") from exc
    if fmt == "yaml":
        try:
            return parse_structured(yaml.safe_load(text))
        except yaml.YAMLError as exc:
            raise RosterError(f"invalid YAML: {exc}") from exc
    if fmt == "text":
        return parse_group_members_text(text)
    raise RosterError(f"unknown roster format {fmt!r}")


def load_roster(path: str | Path) -> Roster:
    """Load a roster from ``path``; ``"-"`` reads stdin."""
    if str(path) == "-":
        return parse_roster_text(sys.stdin.read())
    p = Path(path)
    fmt = {".json": "json", ".yaml": "yaml", ".yml": "yaml"}.get(p.suffix.lower())
    return parse_roster_text(p.read_text(encoding="utf-8"), fmt)


def check_roster(roster: Roster) -> list[str]:
    """Consistency problems that do not prevent parsing (returned as messages)."""
    problems = []
    seen: dict[str, str] = {}
    orcids: dict[str, str] = {}
    variant_owner: dict[str, str] = {}
    names = {normalize_name(e.name) for e in roster.entries}
    for e in roster.entries:
        key = normalize_name(e.name)
        if key in seen:
            problems.append(f"duplicate person {e.name!r} (roles {seen[key]} and {e.role})")
        seen[key] = e.role
        if e.orcid:
            if e.orcid in orcids and orcids[e.orcid] != key:
                problems.append(f"ORCID {e.orcid} shared by {orcids[e.orcid]!r} and {e.name!r}")
            orcids[e.orcid] = key
        for other in e.associated_with:
            if normalize_name(other) not in names:
                problems.append(f"{e.name!r}: associated_with {other!r} is not in the roster")
        for v in name_variants(e.name, e.variants).full:
            owner = variant_owner.setdefault(v, key)
            if owner != key:
                problems.append(f"name variant {v!r} is shared by {owner!r} and {key!r}")
    return problems
